CREATE DATABASE IF NOT EXISTS satukes CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE satukes;

CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL, password_hash VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1, last_login_at DATETIME NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_users_email(email), KEY idx_users_active(is_active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE roles (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(60) NOT NULL, label VARCHAR(100) NOT NULL, UNIQUE KEY uq_roles_name(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE permissions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, label VARCHAR(150) NOT NULL, UNIQUE KEY uq_permissions_name(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE user_roles (user_id BIGINT UNSIGNED NOT NULL, role_id INT UNSIGNED NOT NULL, PRIMARY KEY(user_id,role_id), CONSTRAINT fk_ur_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_ur_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE role_permissions (role_id INT UNSIGNED NOT NULL, permission_id INT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id), CONSTRAINT fk_rp_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, CONSTRAINT fk_rp_perm FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE branches (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(30) NOT NULL, name VARCHAR(150) NOT NULL, base_url VARCHAR(255) NOT NULL, cons_id VARCHAR(100) NOT NULL, secret_ciphertext TEXT NOT NULL, timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Jakarta', status ENUM('active','inactive') NOT NULL DEFAULT 'active', last_sync_at DATETIME NULL, last_sync_status ENUM('success','failed') NULL, last_sync_message VARCHAR(500) NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, UNIQUE KEY uq_branches_code(code), KEY idx_branches_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE user_branches (user_id BIGINT UNSIGNED NOT NULL, branch_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(user_id,branch_id), CONSTRAINT fk_ub_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT fk_ub_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE visit_daily (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, branch_id BIGINT UNSIGNED NOT NULL, visit_date DATE NOT NULL, total_visits INT UNSIGNED NOT NULL DEFAULT 0, source_generated_at DATETIME NULL, synced_at DATETIME NOT NULL, UNIQUE KEY uq_visit_branch_date(branch_id,visit_date), KEY idx_visit_date(visit_date), CONSTRAINT fk_visit_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE sync_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, branch_id BIGINT UNSIGNED NOT NULL, date_from DATE NOT NULL, date_to DATE NOT NULL, status ENUM('success','failed') NOT NULL, records_synced INT UNSIGNED NOT NULL DEFAULT 0, duration_ms INT UNSIGNED NOT NULL DEFAULT 0, message VARCHAR(500) NULL, triggered_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL, KEY idx_sync_branch_created(branch_id,created_at), KEY idx_sync_status_created(status,created_at), CONSTRAINT fk_sync_branch FOREIGN KEY(branch_id) REFERENCES branches(id) ON DELETE CASCADE, CONSTRAINT fk_sync_user FOREIGN KEY(triggered_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE login_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL, ip_address VARCHAR(45) NOT NULL, success TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, KEY idx_login_throttle(email,ip_address,created_at), KEY idx_login_cleanup(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(60) NOT NULL, entity_id BIGINT UNSIGNED NULL, ip_address VARCHAR(45) NOT NULL, metadata JSON NULL, created_at DATETIME NOT NULL, KEY idx_audit_created(created_at), KEY idx_audit_entity(entity_type,entity_id), CONSTRAINT fk_audit_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Development default setelah menjalankan `php index.php cli/install`:
-- admin@example.id / admin123345
-- Pada production, set INSTALL_ADMIN_EMAIL dan INSTALL_ADMIN_PASSWORD terlebih dahulu.
