<div class="page-header d-print-none mb-3"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Monitoring fasilitas kesehatan</div><h2 class="page-title">Dashboard Kunjungan Faskes</h2><div class="text-secondary mt-1">Menampilkan data: <span class="badge bg-teal-lt"><?= $selectedBranch ? html_escape($selectedBranch->code.' · '.$selectedBranch->name) : 'Semua faskes yang dapat diakses' ?></span></div></div><div class="col-auto ms-auto"><form class="btn-list" method="get"><?php if($selectedBranchId): ?><input type="hidden" name="branch_id" value="<?= (int)$selectedBranchId ?>"><?php endif ?><input class="form-control" type="date" name="date_from" value="<?= html_escape($from) ?>" aria-label="Tanggal awal"><input class="form-control" type="date" name="date_to" value="<?= html_escape($to) ?>" aria-label="Tanggal akhir"><button class="btn btn-teal">Terapkan</button></form></div></div></div>
<div class="row row-deck row-cards">
  <div class="col-sm-6 col-lg-4"><div class="card"><div class="card-body d-flex align-items-center"><div class="metric-icon bg-teal-lt text-teal me-3">↗</div><div><div class="text-secondary">Total kunjungan</div><div class="h1 mb-0"><?= number_format((int)$summary->total_visits,0,',','.') ?></div><small class="text-secondary"><?= date('d M',strtotime($from)) ?>–<?= date('d M Y',strtotime($to)) ?></small></div></div></div></div>
  <div class="col-sm-6 col-lg-4"><div class="card"><div class="card-body d-flex align-items-center"><div class="metric-icon bg-blue-lt text-blue me-3">⌂</div><div><div class="text-secondary">Faskes dalam tampilan</div><div class="h1 mb-0"><?= number_format($branchCount) ?></div><small class="text-secondary"><?= (int)$summary->reporting_branches ?> mengirim data pada periode ini</small></div></div></div></div>
  <div class="col-sm-6 col-lg-4"><div class="card"><div class="card-body d-flex align-items-center"><div class="metric-icon bg-azure-lt text-azure me-3">≈</div><div><div class="text-secondary">Rata-rata per hari</div><div class="h1 mb-0"><?php $days=max(1,(strtotime($to)-strtotime($from))/86400+1); echo number_format($summary->total_visits/$days,0,',','.'); ?></div><small class="text-secondary">Agregat seluruh faskes</small></div></div></div></div>
  <div class="col-sm-6 col-lg-4"><div class="card"><div class="card-body"><div class="text-secondary">Pasien baru / lama</div><div class="h2 mb-0"><?= number_format($summary->new_patients,0,',','.') ?> <span class="text-secondary">/</span> <?= number_format($summary->returning_patients,0,',','.') ?></div></div></div></div>
  <div class="col-sm-6 col-lg-4"><div class="card"><div class="card-body"><div class="text-secondary">Rawat jalan / rawat inap</div><div class="h2 mb-0"><?= number_format($summary->total_outpatient_visits,0,',','.') ?> <span class="text-secondary">/</span> <?= number_format($summary->total_inpatient_visits,0,',','.') ?></div></div></div></div>
  <div class="col-sm-6 col-lg-4"><div class="card"><div class="card-body"><div class="text-secondary">Gawat darurat / dirujuk</div><div class="h2 mb-0"><?= number_format($summary->total_emergency_patients,0,',','.') ?> <span class="text-secondary">/</span> <?= number_format($summary->total_referred_patients,0,',','.') ?></div></div></div></div>
  <div class="col-lg-8"><div class="card"><div class="card-header"><h3 class="card-title">Tren kunjungan harian</h3></div><div class="card-body"><div class="chart" role="img" aria-label="Grafik kunjungan harian"><?php $max=max(array_merge(array(1),array_map(fn($d)=>(int)$d->total_visits,$daily))); foreach($daily as $d): ?><div class="chart-item" title="<?= date('d M Y',strtotime($d->visit_date)) ?>: <?= (int)$d->total_visits ?> kunjungan"><div class="small fw-bold"><?= (int)$d->total_visits ?></div><div class="chart-bar" style="height:<?= max(3,round($d->total_visits/$max*160)) ?>px"></div><div class="chart-label"><?= date('d M',strtotime($d->visit_date)) ?></div></div><?php endforeach ?><?php if(!$daily): ?><div class="text-secondary m-auto">Belum ada data. Jalankan sinkronisasi faskes.</div><?php endif ?></div></div></div></div>
  <div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">Kontribusi faskes</h3></div><div class="list-group list-group-flush list-group-hoverable"><?php foreach($branchStats as $b): ?><div class="list-group-item"><div class="row align-items-center"><div class="col"><div class="fw-semibold"><?= html_escape($b->name) ?></div><div class="text-secondary small"><?= html_escape($b->code) ?> · <?= $b->last_sync_at ? 'sinkron '.date('d M H:i',strtotime($b->last_sync_at)) : 'belum sinkron' ?></div></div><div class="col-auto"><span class="badge bg-teal-lt"><?= number_format($b->total_visits,0,',','.') ?></span></div></div></div><?php endforeach ?><?php if(!$branchStats): ?><div class="card-body text-secondary">Belum ada faskes yang dapat Anda akses.</div><?php endif ?></div></div></div>
  <div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">Cara bayar</h3></div><div class="table-responsive"><table class="table card-table table-vcenter"><tbody><?php foreach($paymentMethods as $item): ?><tr><td><div class="fw-semibold"><?= html_escape($item['payment_name']) ?></div><small class="text-secondary"><?= html_escape($item['payment_code']) ?></small></td><td class="text-end"><?= number_format($item['total_patients'],0,',','.') ?></td></tr><?php endforeach ?><?php if(!$paymentMethods): ?><tr><td class="text-secondary">Belum ada data.</td></tr><?php endif ?></tbody></table></div></div></div>
  <div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">10 diagnosa terbanyak</h3></div><div class="table-responsive"><table class="table card-table table-vcenter"><tbody><?php foreach($diagnoses as $item): ?><tr><td class="text-secondary"><?= $item['rank'] ?></td><td><div class="fw-semibold"><?= html_escape($item['diagnosis_name']) ?></div><small class="text-secondary"><?= html_escape($item['diagnosis_code']) ?></small></td><td class="text-end"><?= number_format($item['total_patients'],0,',','.') ?></td></tr><?php endforeach ?><?php if(!$diagnoses): ?><tr><td class="text-secondary">Belum ada data.</td></tr><?php endif ?></tbody></table></div></div></div>
  <div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">10 obat terbanyak</h3></div><div class="table-responsive"><table class="table card-table table-vcenter"><tbody><?php foreach($medicines as $item): ?><tr><td class="text-secondary"><?= $item['rank'] ?></td><td><div class="fw-semibold"><?= html_escape($item['medicine_name']) ?></div><small class="text-secondary"><?= html_escape($item['medicine_code']) ?> · <?= number_format($item['total_prescriptions'],0,',','.') ?> resep</small></td><td class="text-end"><?= number_format($item['total_quantity'],0,',','.') ?></td></tr><?php endforeach ?><?php if(!$medicines): ?><tr><td class="text-secondary">Belum ada data.</td></tr><?php endif ?></tbody></table></div></div></div>
</div>
